frontend:
        container_name: frontend
        build: frontend/
        ports:
                - "80:5000"
        environment: 
                ENV: "DEV"
        volumes:
                - '/home/tony/passwordGenerator/frontend/app/:/app'
        links: 
                - backend
backend:     
        container_name: backend
        build: backend/
        ports:
                - "7777:7777"
        environment:
                ENV: "DEV"
